// dom.ts — the element handles the shell needs, looked up once and typed.

/** Fetch an element by id, or fail loudly: a missing id is a broken index.html. */
function el<T extends HTMLElement>(id: string): T {
  const node = document.getElementById(id);
  if (!node) throw new Error(`index.html is missing #${id}`);
  return node as T;
}

/** Every element ui.ts touches. Built once, at startup. */
export function queryDom() {
  return {
    canvas: el<HTMLCanvasElement>('view'),
    dropzone: el('dropzone'),
    toast: el('toast'),

    examples: el<HTMLSelectElement>('examples'),
    play: el<HTMLButtonElement>('play'),
    modeToggle: el<HTMLButtonElement>('mode-toggle'),

    toolbar: el('toolbar'),
    tools: [...document.querySelectorAll<HTMLButtonElement>('#toolbar .tool')],
    directions: [...document.querySelectorAll<HTMLButtonElement>('#toolbar .dir')],
    wireColor: el<HTMLButtonElement>('wire-color'),
    wireSwatch: el('wire-swatch'),
    palette: el('palette'),
    paletteGrid: el('palette-grid'),
    paletteInput: el<HTMLInputElement>('palette-input'),
    paletteAdd: el<HTMLButtonElement>('palette-add'),
    busWidth: el<HTMLInputElement>('bus-width'),
    rotateCw: el<HTMLButtonElement>('rotate-cw'),
    rotateCcw: el<HTMLButtonElement>('rotate-ccw'),
    camera: el<HTMLSelectElement>('camera'),
    undo: el<HTMLButtonElement>('undo'),
    redo: el<HTMLButtonElement>('redo'),
    save: el<HTMLButtonElement>('save'),
    dirtyFlag: el('dirty-flag'),
    settings: el('settings'),
    settingsToggle: el<HTMLButtonElement>('settings-toggle'),
    settingsClose: el<HTMLButtonElement>('settings-close'),

    analysisToggle: el<HTMLButtonElement>('analysis-toggle'),
    analysisToolbar: el('analysis-toolbar'),
    schematicCanvas: el<HTMLCanvasElement>('schematic-view'),
    viewPixels: el<HTMLButtonElement>('view-pixels'),
    viewSchematic: el<HTMLButtonElement>('view-schematic'),
    levelGroup: el('level-group'),
    levelRecognised: el<HTMLButtonElement>('level-recognised'),
    levelFaithful: el<HTMLButtonElement>('level-faithful'),
    analysisSelect: el<HTMLButtonElement>('analysis-select'),
    analysisRunToolbar: el<HTMLButtonElement>('analysis-run-toolbar'),
    analysisPanelToggle: el<HTMLButtonElement>('analysis-panel-toggle'),
    analysis: el('analysis'),
    analysisClose: el<HTMLButtonElement>('analysis-close'),
    analysisRun: el<HTMLButtonElement>('analysis-run'),
    analysisAbort: el<HTMLButtonElement>('analysis-abort'),
    analysisOracle: el<HTMLInputElement>('analysis-oracle'),
    analysisSimplify: el<HTMLInputElement>('analysis-simplify'),
    analysisPowerOn: el<HTMLInputElement>('analysis-poweron'),
    analysisStorageGroup: el('analysis-storage-group'),
    analysisStorageSummary: el('analysis-storage-summary'),
    analysisStorageList: el('analysis-storage-list'),
    analysisProgress: el<HTMLProgressElement>('analysis-progress'),
    analysisStale: el('analysis-stale'),
    analysisStatus: el('analysis-status'),
    analysisShapeGroup: el('analysis-shape-group'),
    analysisShape: el('analysis-shape'),
    analysisNotes: el('analysis-notes'),
    analysisIoGroup: el('analysis-io-group'),
    analysisInputs: el('analysis-inputs'),
    analysisOutputs: el('analysis-outputs'),
    analysisInternal: el('analysis-internal'),
    analysisCut: el('analysis-cut'),
    analysisUnresolved: el('analysis-unresolved'),
    labelsSave: el<HTMLButtonElement>('labels-save'),
    labelsLoad: el<HTMLButtonElement>('labels-load'),
    labelsClear: el<HTMLButtonElement>('labels-clear'),
    analysisTableGroup: el('analysis-table-group'),
    analysisTable: el('analysis-table'),
    analysisOracleGroup: el('analysis-oracle-group'),
    analysisVerdict: el('analysis-verdict'),
    analysisDiscrepancies: el('analysis-discrepancies'),
    analysisSimplifyGroup: el('analysis-simplify-group'),
    analysisCost: el('analysis-cost'),
    analysisExpressions: el('analysis-expressions'),
    analysisReplace: el<HTMLButtonElement>('analysis-replace'),
    analysisExport: el<HTMLButtonElement>('analysis-export'),
    analysisImport: el<HTMLButtonElement>('analysis-import'),

    openFile: el<HTMLButtonElement>('open-file'),
    reset: el<HTMLButtonElement>('reset'),
    fit: el<HTMLButtonElement>('fit'),
    fileName: el('file-name'),
    liveNote: el('live-note'),

    speed: el<HTMLInputElement>('speed'),
    speedValue: el('speed-value'),
    passes: el<HTMLInputElement>('passes'),
    passesValue: el('passes-value'),
    refresh: el<HTMLInputElement>('refresh'),
    refreshValue: el('refresh-value'),

    statCursor: el('stat-cursor'),
    statCursorField: el<HTMLButtonElement>('stat-cursor-field'),
    statSelectionField: el<HTMLButtonElement>('stat-selection-field'),
    statusbar: el('statusbar'),
    copyStatus: el<HTMLButtonElement>('copy-status'),
    copyable: [...document.querySelectorAll<HTMLButtonElement>('#statusbar .copyable')],
    statSize: el('stat-size'),
    statWires: el('stat-wires'),
    statGates: el('stat-gates'),
    statCycle: el('stat-cycle'),
    statRate: el('stat-rate'),
    statFps: el('stat-fps'),
    zoomValue: el('zoom-value'),
  };
}

export type Dom = ReturnType<typeof queryDom>;
